services:
  r_interco_1:
    build:
      context: ./R_Interco_1
    networks:
      Res_Coeur:
        ipv4_address: 120.0.160.4
     

  r_interco_2:
    build:
      context: ./R_Interco_2
    networks:
      Res_Coeur:
        ipv4_address: 120.0.160.3
     

  r_entreprise:
    build:
      context: ./R_Entreprise
    networks:
      Res_Coeur:
        ipv4_address: 120.0.160.2
      Res_Entreprise_Prim:
        ipv4_address: 120.0.168.2
  
  r_clients:
    build:
      context: ./R_Clients
    networks:
      Res_Coeur:
        ipv4_address: 120.0.160.7
      Res_Clients:
        ipv4_address: 120.0.172.9
        
  box:
    build:
      context: ./Box
    networks:
      Res_Particulier:
        ipv4_address: 192.168.1.2
      Res_Clients:
        ipv4_address: 120.0.172.3

networks:
  Res_Coeur:
    driver: bridge
    ipam:
      config:
        - subnet: 120.0.160.0/21
  Res_Entreprise_Prim:
    driver: bridge
    ipam:
      config:
        - subnet: 120.0.168.0/22
  Res_Clients:
    driver: bridge
    ipam:
      config:
        - subnet: 120.0.172.0/22
  Res_Particulier:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
    