services:
  r_interco:
    build:
      context: ./R_Interco
    cap_add:
      - NET_ADMIN  
    networks:
      Res_Coeur:
        ipv4_address: 120.0.160.3
     

  r_dmz:
    build:
      context: ./R_DMZ
    cap_add:
      - NET_ADMIN
    networks:
      Res_Coeur:
        ipv4_address: 120.0.160.4
      Res_DMZ:
        ipv4_address: 120.0.174.4
     

  r_entreprise_prim:
    build:
      context: ./R_Entreprise_Prim
    cap_add:
      - NET_ADMIN
    networks:
      Res_Coeur:
        ipv4_address: 120.0.160.2
      Res_Entreprise_Prim_Public:
        ipv4_address: 120.0.168.2

  r_entreprise_secon:
    build:
      context: ./R_Entreprise_Secon
    cap_add:
      - NET_ADMIN
    networks:
      Res_Coeur:
        ipv4_address: 120.0.160.6
      
  
  r_clients:
    build:
      context: ./R_Clients
    cap_add:
      - NET_ADMIN
    networks:
      Res_Coeur:
        ipv4_address: 120.0.160.5
      Res_Clients:
        ipv4_address: 120.0.172.2
        
  box:
    build:
      context: ./Box
    cap_add:
      - NET_ADMIN
    networks:
      Res_Particulier:
        ipv4_address: 192.168.0.5
      Res_Clients:
        ipv4_address: 120.0.172.3

networks:
  Res_Coeur:
    driver: bridge
    ipam:
      config:
        - subnet: 120.0.160.0/21
  Res_DMZ: 
    driver: bridge
    ipam: 
      config:
        - subnet: 120.0.174.0/24
  Res_Entreprise_Prim_Public:
    driver: bridge
    ipam:
      config:
        - subnet: 120.0.168.0/22
  Res_Clients:
    driver: bridge
    ipam:
      config:
        - subnet: 120.0.172.0/23
  Res_Particulier:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/23
  Res_Entreprise_Prim_Prive:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
  Res_Entreprise_Secon_Prive:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.3.0/24
    
    