services:
  r_interco:
    build:
      context: ./R_Interco
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      Res_Coeur:
        ipv4_address: 120.0.160.3
    dns:
      - 120.0.168.5 ##Pour tester on met dns entreprise mais c'est le dns DMZ qui doit être mis je penses
    volumes:
      - ./R_Interco/config/frr.conf:/etc/frr/frr.conf

     

  r_dmz:
    build:
      context: ./R_DMZ
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      Res_Coeur:
        ipv4_address: 120.0.160.4
      Res_DMZ:
        ipv4_address: 120.0.174.4
    dns:
      - 120.0.168.5 ##Ici dns DMZ
    volumes:
      - ./R_Interco/config/frr.conf:/etc/frr/frr.conf

     

  r_entreprise_prim:
    build:
      context: ./R_Entreprise_Prim
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      Res_Coeur:
        ipv4_address: 120.0.160.2
      Res_Entreprise_Prim_Public:
        ipv4_address: 120.0.168.2
    dns:
      - 120.0.168.5 ##Ici dns entreprise
    volumes:
      - ./R_Interco/config/frr.conf:/etc/frr/frr.conf
    
    
  r_entreprise_secon:
    build:
      context: ./R_Entreprise_Secon
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      Res_Coeur:
        ipv4_address: 120.0.160.6
    dns:
      - 120.0.168.5 ##Ici dns DMZ
    volumes:
      - ./R_Interco/config/frr.conf:/etc/frr/frr.conf

      
  
  r_clients:
    build:
      context: ./R_Clients
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      Res_Coeur:
        ipv4_address: 120.0.160.5
      Res_Clients:
        ipv4_address: 120.0.172.2
    dns:
      - 120.0.168.5 
    volumes:
      - ./R_Interco/config/frr.conf:/etc/frr/frr.conf

        


  serveurdns:
    build:
      context: ./ServeurDNS  
    cap_add:
      - NET_ADMIN  
    privileged: true
    networks:
      Res_Entreprise_Prim_Public:
        ipv4_address: 120.0.168.5  
    volumes:
      - ./ServeurDNS/named.conf:/etc/bind/named.conf
      - ./ServeurDNS/db.entreprise10.com:/etc/bind/db.entreprise10.com

  serveurweb:
    build:
      context: ./ServeurWEB 
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      Res_Entreprise_Prim_Public:
        ipv4_address: 120.0.168.4
    ports:
      - "8000:8010"  
    volumes:
      - ./ServeurWEB/index.html:/var/www/html/index.html  
  serveurdhcp:
    build:
      context: ./ServeurDHCP
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      Res_Entreprise_Prim_Prive:
        ipv4_address: 192.168.3.12
  r_dom:
    build:
      context: ./R_Dom
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      Res_Domicile:
        ipv4_address: 192.168.2.2
      Res_Clients:
        ipv4_address: 120.0.172.3

  r_entreprise_priv:
    build:
      context: ./R_Entreprise_priv
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      Res_Entreprise_Prim_Public:
        ipv4_address: 120.0.168.3
      Res_Entreprise_Prim_Prive:
        ipv4_address: 192.168.3.5

  client:
    build:
      context: ./Client
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      Res_Domicile:
        ipv4_address: 192.168.2.30

  utilisateur_entreprise:
    build:
      context: ./Utilisateur_entreprise
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      Res_Entreprise_Prim_Prive:
        

  box_sitesecon:
    build:
      context: ./Box_Sitesecon
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      Res_Entreprise_Secon_Prive:
        ipv4_address:  192.168.1.9

  u_secon:
    build:
      context: ./U_Secon
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      Res_Entreprise_Secon_Prive:


networks:
  Res_Coeur:
    driver: bridge
    ipam:
      config:
        - subnet: 120.0.160.0/21
  Res_DMZ: 
    driver: bridge
    ipam: 
      config:
        - subnet: 120.0.174.0/24
  Res_Entreprise_Prim_Public:
    driver: bridge
    ipam:
      config:
        - subnet: 120.0.168.0/22
          
  Res_Clients:
    driver: bridge
    ipam:
      config:
        - subnet: 120.0.172.0/23

  Res_Entreprise_Prim_Prive:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.3.0/24
  Res_Entreprise_Secon_Prive:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
    
  Res_Domicile:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24


