FROM ubuntu/bind9:latest

# Installation de bind9
# RUN apt-get update && apt-get install -y bind9


# Copier les fichiers de configuration dans le conteneur
# COPY named.conf /etc/bind9/
# COPY db.groupe10.com /etc/bind9/
COPY dns.sh /home/dns.sh

# Exposer le port 53 pour DNS
EXPOSE 53/udp

# Lancer le serveur DNS bind9 en mode premier plan
ENTRYPOINT /home/dns.sh