FROM ubuntu/bind9:latest

# Installation de bind9
# RUN apt-get update && apt-get install -y bind9
RUN apt-get update
RUN apt-get -y install iptables apt-utils iproute2 net-tools systemd telnet nano iputils-ping tcpdump inetutils-traceroute apache2 tasksel
RUN apt-get -f install

# Copier les fichiers de configuration dans le conteneur
COPY dns.sh /home/dns.sh

RUN chmod +x /home/dns.sh

RUN chmod +x /home/dns.sh
# Exposer le port 53 pour DNS
EXPOSE 53/udp

# Lancer le serveur DNS bind9 en mode premier plan
ENTRYPOINT /home/dns.sh